services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      DATABASE_URL: psql://media_vault:media_vault@db:5432/media_vault
      REDIS_URL: redis://redis:6379/0
      AWS_S3_ENDPOINT_URL: http://minio:9000
    depends_on:
      - db
      - redis
      - minio
    ports:
      - "8000:8000"
