default:
    @just --list

up:
    docker compose up -d

down:
    docker compose down

run:
    uv run manage.py runserver

migrate:
    uv run manage.py migrate

makemigrations:
    uv run manage.py makemigrations

createsuperuser:
    uv run manage.py createsuperuser

shell:
    uv run manage.py shell

test:
    uv run manage.py test

worker:
    uv run celery -A config worker -l info

beat:
    uv run celery -A config beat -l info
