"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import environ
from celery.schedules import crontab
from django.utils.translation import gettext_lazy as _

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")

DEBUG = env.bool("DJANGO_DEBUG", default=False)
SECRET_KEY = env(
    "DJANGO_SECRET_KEY", default="django-insecure-build-only" if DEBUG else env.NOTSET
)
ALLOWED_HOSTS = env.list(
    "DJANGO_ALLOWED_HOSTS", default=[]
)  # DEBUG already accepts localhost / 127.0.0.1 / [::1]
DATABASES = {
    "default": env.db(
        "DATABASE_URL",
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}" if DEBUG else env.NOTSET,
    )
}  # 4 slashes = absolute, survives running manage.py from any cwd

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Application definition

# `mailauth.contrib.admin` MUST come before `django.contrib.admin` — Django
# resolves admin templates / login view in app order, so the overriding app
# has to load first.
INSTALLED_APPS = [
    "mailauth.contrib.admin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "mailauth",
    "mailauth.contrib.user",
    "jobs",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Auth

AUTHENTICATION_BACKENDS = [
    "mailauth.backends.MailAuthBackend",
]

AUTH_USER_MODEL = "mailauth_user.EmailUser"

LOGIN_URL = "mailauth:login"
LOGIN_REDIRECT_URL = "/"


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en"
USE_I18N = True
USE_TZ = True
TIME_ZONE = "UTC"

LANGUAGES = [
    ("en", _("English")),
]

LOCALE_PATHS = [BASE_DIR / "locale"]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"


# Email
# https://django-environ.readthedocs.io/en/latest/types.html#environ-env-email-url

globals().update(
    env.email_url(
        "EMAIL_URL",
        default="consolemail://" if DEBUG else env.NOTSET,
    )
)

DEFAULT_FROM_EMAIL = env(
    "DEFAULT_FROM_EMAIL",
    default="webmaster@localhost" if DEBUG else env.NOTSET,
)
SERVER_EMAIL = env("SERVER_EMAIL", default=DEFAULT_FROM_EMAIL)

ADMINS = [
    (email.split("@")[0], email) for email in env.list("DJANGO_ADMINS", default=[])
]
MANAGERS = ADMINS


# Redis cache

# Bare scheme://host:port form — no trailing slash, no /<db>. Per-purpose
# DBs are appended below. .rstrip("/") is a defensive guard so a stray
# trailing slash from a managed platform doesn't produce redis://host//0.
REDIS_URL = env("REDIS_URL", default="redis://127.0.0.1:6379").rstrip("/")

# /0 cache, /1 Celery broker, /2 Celery results.
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"{REDIS_URL}/0",
        "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
    }
}


# Celery

CELERY_BROKER_URL = f"{REDIS_URL}/1"
CELERY_RESULT_BACKEND = f"{REDIS_URL}/2"
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True  # silence Celery 5+ deprecation

CELERY_BEAT_SCHEDULE = {
    "daily-digest": {
        "task": "jobs.tasks.send_daily_digest",
        "schedule": crontab(hour=8, minute=0),
    },
}
