# Generated by Django 6.0.7 on 2026-07-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('company', models.CharField(max_length=200, verbose_name='company')),
                ('description', models.TextField(verbose_name='description')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='location')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'job',
                'verbose_name_plural': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
