install:
    uv sync

dev:
    uv run manage.py runserver

migrate:
    uv run manage.py migrate

makemigrations:
    uv run manage.py makemigrations

shell:
    uv run manage.py shell

superuser:
    uv run manage.py createsuperuser

test:
    uv run manage.py test

worker:
    DJANGO_SETTINGS_MODULE=config.settings uv run celery -A config worker -l info

beat:
    DJANGO_SETTINGS_MODULE=config.settings uv run celery -A config beat -l info
