dc := "docker compose exec -T web"

install:
    docker compose build

dev:
    docker compose up

migrate:
    {{dc}} python manage.py migrate

makemigrations:
    {{dc}} python manage.py makemigrations

test:
    {{dc}} python manage.py test

shell:
    docker compose exec web python manage.py shell

superuser:
    docker compose exec web python manage.py createsuperuser
